### PR TITLE
updated cfg file name to prevent rebuilding every time

### PR DESCRIPTION
**Pull request by flaviofontana**
Hi there 

I changed the name of the cfg file to prevent the regeneration of the header files and the resulting recompiling of the ssf package.

exit(gen.generate(PACKAGE, "dynamic_tutorials", "Tutorials"))

The third parameter is a name prefix the generated files will get (e.g. "<name>Config.h"
The third parameter should be equal to the cfg file name, without extension. Otherwise the libraries will be generated in every build, forcing a recompilation of the nodes which use them. 

(http://wiki.ros.org/dynamic_reconfigure/Tutorials/HowToWriteYourFirstCfgFile)

### CODE REVIEW

**Comment by flaviofontana** [comment]
I also added the cmake modules dependency in order to build in ros indigo

**Comment by markusachtelik** [comment]
thanks a lot! It's surprizing to me that there were no other changes required from the renaming. Could you try to make a clean build? Otherwise I'm happy to merge

**Comment by simonlynen** [comment]
Can one of the admins verify this patch?

**Comment by simonlynen** [comment]
test this please

**Comment by flaviofontana** [comment]
thanks for merging

**Pull request merged**
